- name: "configuration play." 
  hosts: web
  pre_tasks:
    - name: "wait 100 seconds for target connection to become reachable/usable."
      wait_for:
        timeout: 100
  user: ec2-user
  gather_facts: false
    #- name: "install python for Ansible."
      # Your code here

  roles:
    - configure-server